### ISSUE TITLE
Problem with deploying secure nifi container with docker compose

### ISSUE THREAD

**Issue by samer1977** [robcowart/docker_compose_cookbook#1]
Hi,
Im trying to follow your template to deploy a secure (TLS) nifi container using docker compose (yml), however it keeps defaulting to HTTP 8080 port. Not sure what Im doing wrong. Can you please help? Here is my yml script:
```

version: "3.5"
services:
    nifi:
        image: apache/nifi:latest
        container_name: nifi
        restart: unless-stopped
        network_mode: bridge
        ports:
            - "8443:8443"
        volumes:
            - /certs:/opt/certs
  
        environment:
            NIFI_WEB_HTTPS_HOST: '0.0.0.0'
            NIFI_WEB_HTTPS_PORT: 8443
            KEYSTORE_PATH: '/opt/certs/keystore.jks'
            KEYSTORE_PASSWORD: '*************************************************'
            KEYSTORE_TYPE: JKS
            KEY_PASSWORD: '****************************************************'
            TRUSTSTORE_PATH: '/opt/certs/truststore.jks'
            TRUSTSTORE_PASSWORD: '***********************************************'
            TRUSTSTORE_TYPE: JKS
            INITIAL_ADMIN_IDENTITY: 'CN=my_user, OU=NiFi'


```
